<?php
defined('BASEPATH') OR exit('No direct script access allowed');

require APPPATH . 'libraries/REST_Controller.php';

class Pebhdr extends REST_Controller {
	
	function __construct()
	{
		// Construct the parent class
		parent::__construct();
		$this->db = $this->load->database('dev_peb_pli', TRUE);
	}
	
	function index_get() {
		
        //id	CAR	JnEks	KatEks	JNPEB	JNEKSOld	JNLAIN	JNDAG	JNBYR	IDEKS	NPWPEKS	NamaEks	AlmtEks	NoSiup	TgSiup	JnPerus	NoTdp	TgTdp	Niper	StatusH	IdQq	NpwpQq	NamaQq	AlmtQq	NiperQq	NAMABELI	ALMTBELI	NEGBELI	IDPPJK	NPWPPPJK	NamaPpjk	AlmtPpjk	NoPpjk	TgPpjk	MODA	TGEKS	CARRIER	VOY	NOSHIPORD	TGSHIPORD	PELMUAT	PELBONGKAR	PELTRANSIT	NOINV	TGINV	NOLPSE	TGLPSE	PROPBRG	NEGTUJU	FLSIE	FLKARANT	FLSM	FLIZLAIN	DELIVERY	KDVAL	KdHrg	NilInv	FREIGHT	ASURANSI	KdAss	FOB	MERK	JMCONT	BRUTO	NETTO	JMBRG	JMBRGCTH	JMBRGGAB	JMBRGPJT	NODAFT	TGDAFT	KDKTR	KTRGATE	NILPE	KDBANK	LOKBANK	NOSSP	TGSSP	JNTPB	LOKTPB	KDLOKBRG	KDKTRMUAT	KDKTRPRIKS	TGSIAP	WKSIAP	ASALDATA	TPNAME	PEBOK	LENGKAP	JNPARTOF	BENDERA	TTDPEB	STATUS	SNRF	NOBCF	TGBCF	SERIBCF	NOMOREDI	KMDT	VOLUME	KDHANGGAR	KONS	JMLKMSPEB	PELMUATEKS	NILKURS	PNBP	NOBC11	TGBC11	POSBC11	SUBPOSBC11	TGL_BERLAKU_TOD	KDKTREKS	PELTUJUAN	NAMABELI2	ALMTBELI2	NEGBELI2	VERSIMODUL	NILMAKLON	NILPAJAKLAIN	URCARABAYAR	GUDANGPLB	PERNYATAAN	flKdVAL	flFOB	flNilMaklon
		$id = $this->get('id');
        if ($id == '') {
			$data = $this->db->get('temp_pebhdr')->result();            
        } else {
            $this->db->where('id', $id);
            $data = $this->db->get('temp_pebhdr')->result();
        }
        $this->response($data, 200);
    }
	
	function index_put() {
		$id = $this->put('id');
        $data = array(
					'CAR'				=> $this->put('CAR'),
					'JnEks'				=> $this->put('JnEks'),
					'KatEks'			=> $this->put('KatEks'),
					'JNPEB'				=> $this->put('JNPEB'),
					'JNEKSOld'			=> $this->put('JNEKSOld'),
					'JNLAIN'			=> $this->put('JNLAIN'),
					'JNDAG'				=> $this->put('JNDAG'),
					'JNBYR'				=> $this->put('JNBYR'),
					'IDEKS'				=> $this->put('IDEKS'),
					'NPWPEKS'			=> $this->put('NPWPEKS'),
					'NamaEks'			=> $this->put('NamaEks'),
					'AlmtEks'			=> $this->put('AlmtEks'),
					'NoSiup'			=> $this->put('NoSiup'),
					'TgSiup'			=> $this->put('TgSiup'),
					'JnPerus'			=> $this->put('JnPerus'),
					'NoTdp'				=> $this->put('NoTdp'),
					'TgTdp'				=> $this->put('TgTdp'),
					'Niper'				=> $this->put('Niper'),
					'StatusH'			=> $this->put('StatusH'),
					'IdQq'				=> $this->put('IdQq'),
					'NpwpQq'			=> $this->put('NpwpQq'),
					'NamaQq'			=> $this->put('NamaQq'),
					'AlmtQq'			=> $this->put('AlmtQq'),
					'NiperQq'			=> $this->put('NiperQq'),
					'NAMABELI'			=> $this->put('NAMABELI'),
					'ALMTBELI'			=> $this->put('ALMTBELI'),
					'NEGBELI'			=> $this->put('NEGBELI'),
					'IDPPJK'			=> $this->put('IDPPJK'),
					'NPWPPPJK'			=> $this->put('NPWPPPJK'),
					'NamaPpjk'			=> $this->put('NamaPpjk'),
					'AlmtPpjk'			=> $this->put('AlmtPpjk'),
					'NoPpjk'			=> $this->put('NoPpjk'),
					'TgPpjk'			=> $this->put('TgPpjk'),
					'MODA'				=> $this->put('MODA'),
					'TGEKS'				=> $this->put('TGEKS'),
					'CARRIER'			=> $this->put('CARRIER'),
					'VOY'				=> $this->put('VOY'),
					'NOSHIPORD'			=> $this->put('NOSHIPORD'),
					'TGSHIPORD'			=> $this->put('TGSHIPORD'),
					'PELMUAT'			=> $this->put('PELMUAT'),
					'PELBONGKAR'		=> $this->put('PELBONGKAR'),
					'PELTRANSIT'		=> $this->put('PELTRANSIT'),
					'NOINV'				=> $this->put('NOINV'),
					'TGINV'				=> $this->put('TGINV'),
					'NOLPSE'			=> $this->put('NOLPSE'),
					'TGLPSE'			=> $this->put('TGLPSE'),
					'PROPBRG'			=> $this->put('PROPBRG'),
					'NEGTUJU'			=> $this->put('NEGTUJU'),
					'FLSIE'				=> $this->put('FLSIE'),
					'FLKARANT'			=> $this->put('FLKARANT'),
					'FLSM'				=> $this->put('FLSM'),
					'FLIZLAIN'			=> $this->put('FLIZLAIN'),
					'DELIVERY'			=> $this->put('DELIVERY'),
					'KDVAL'				=> $this->put('KDVAL'),
					'KdHrg'				=> $this->put('KdHrg'),
					'NilInv'			=> $this->put('NilInv'),
					'FREIGHT'			=> $this->put('FREIGHT'),
					'ASURANSI'			=> $this->put('ASURANSI'),
					'KdAss'				=> $this->put('KdAss'),
					'FOB'				=> $this->put('FOB'),
					'MERK'				=> $this->put('MERK'),
					'JMCONT'			=> $this->put('JMCONT'),
					'BRUTO'				=> $this->put('BRUTO'),
					'NETTO'				=> $this->put('NETTO'),
					'JMBRG'				=> $this->put('JMBRG'),
					'JMBRGCTH'			=> $this->put('JMBRGCTH'),
					'JMBRGGAB'			=> $this->put('JMBRGGAB'),
					'JMBRGPJT'			=> $this->put('JMBRGPJT'),
					'NODAFT'			=> $this->put('NODAFT'),
					'TGDAFT'			=> $this->put('TGDAFT'),
					'KDKTR'				=> $this->put('KDKTR'),
					'KTRGATE'			=> $this->put('KTRGATE'),
					'NILPE'				=> $this->put('NILPE'),
					'KDBANK'			=> $this->put('KDBANK'),
					'LOKBANK'			=> $this->put('LOKBANK'),
					'NOSSP'				=> $this->put('NOSSP'),
					'TGSSP'				=> $this->put('TGSSP'),
					'JNTPB'				=> $this->put('JNTPB'),
					'LOKTPB'			=> $this->put('LOKTPB'),
					'KDLOKBRG'			=> $this->put('KDLOKBRG'),
					'KDKTRMUAT'			=> $this->put('KDKTRMUAT'),
					'KDKTRPRIKS'		=> $this->put('KDKTRPRIKS'),
					'TGSIAP'			=> $this->put('TGSIAP'),
					'WKSIAP'			=> $this->put('WKSIAP'),
					'ASALDATA'			=> $this->put('ASALDATA'),
					'TPNAME'			=> $this->put('TPNAME'),
					'PEBOK'				=> $this->put('PEBOK'),
					'LENGKAP'			=> $this->put('LENGKAP'),
					'JNPARTOF'			=> $this->put('JNPARTOF'),
					'BENDERA'			=> $this->put('BENDERA'),
					'TTDPEB'			=> $this->put('TTDPEB'),
					'STATUS'			=> $this->put('STATUS'),
					'SNRF'				=> $this->put('SNRF'),
					'NOBCF'				=> $this->put('NOBCF'),
					'TGBCF'				=> $this->put('TGBCF'),
					'SERIBCF'			=> $this->put('SERIBCF'),
					'NOMOREDI'			=> $this->put('NOMOREDI'),
					'KMDT'				=> $this->put('KMDT'),
					'VOLUME'			=> $this->put('VOLUME'),
					'KDHANGGAR'			=> $this->put('KDHANGGAR'),
					'KONS'				=> $this->put('KONS'),
					'JMLKMSPEB'			=> $this->put('JMLKMSPEB'),
					'PELMUATEKS'		=> $this->put('PELMUATEKS'),
					'NILKURS'			=> $this->put('NILKURS'),
					'PNBP'				=> $this->put('PNBP'),
					'NOBC11'			=> $this->put('NOBC11'),
					'TGBC11'			=> $this->put('TGBC11'),
					'POSBC11'			=> $this->put('POSBC11'),
					'SUBPOSBC11'		=> $this->put('SUBPOSBC11'),
					'TGL_BERLAKU_TOD'	=> $this->put('TGL_BERLAKU_TOD'),
					'KDKTREKS'			=> $this->put('KDKTREKS'),
					'PELTUJUAN'			=> $this->put('PELTUJUAN'),
					'NAMABELI2'			=> $this->put('NAMABELI2'),
					'ALMTBELI2'			=> $this->put('ALMTBELI2'),
					'NEGBELI2'			=> $this->put('NEGBELI2'),
					'VERSIMODUL'		=> $this->put('VERSIMODUL'),
					'NILMAKLON'			=> $this->put('NILMAKLON'),
					'NILPAJAKLAIN'		=> $this->put('NILPAJAKLAIN'),
					'URCARABAYAR'		=> $this->put('URCARABAYAR'),
					'GUDANGPLB'			=> $this->put('GUDANGPLB'),
					'PERNYATAAN'		=> $this->put('PERNYATAAN'),
					'flKdVAL'			=> $this->put('flKdVAL'),
					'flFOB'				=> $this->put('flFOB'),
					'flNilMaklon'		=> $this->put('flNilMaklon')				
					);
					
		$this->db->where('id', $id);
        $update = $this->db->update('temp_pebhdr', $data);
        if ($update) {
            $this->response($data, 200);
        } else {
            $this->response(array('status' => 'fail', 502));
        }
	}
	function index_post() {		
        $data = array(		
					'CAR'			=> $this->post('CAR'),
					'JnEks'				=> $this->post('JnEks'),
					'KatEks'			=> $this->post('KatEks'),
					'JNPEB'				=> $this->post('JNPEB'),
					'JNEKSOld'			=> $this->post('JNEKSOld'),
					'JNLAIN'			=> $this->post('JNLAIN'),
					'JNDAG'				=> $this->post('JNDAG'),
					'JNBYR'				=> $this->post('JNBYR'),
					'IDEKS'				=> $this->post('IDEKS'),
					'NPWPEKS'			=> $this->post('NPWPEKS'),
					'NamaEks'			=> $this->post('NamaEks'),
					'AlmtEks'			=> $this->post('AlmtEks'),
					'NoSiup'			=> $this->post('NoSiup'),
					'TgSiup'			=> $this->post('TgSiup'),
					'JnPerus'			=> $this->post('JnPerus'),
					'NoTdp'				=> $this->post('NoTdp'),
					'TgTdp'				=> $this->post('TgTdp'),
					'Niper'				=> $this->post('Niper'),
					'StatusH'			=> $this->post('StatusH'),
					'IdQq'				=> $this->post('IdQq'),
					'NpwpQq'			=> $this->post('NpwpQq'),
					'NamaQq'			=> $this->post('NamaQq'),
					'AlmtQq'			=> $this->post('AlmtQq'),
					'NiperQq'			=> $this->post('NiperQq'),
					'NAMABELI'			=> $this->post('NAMABELI'),
					'ALMTBELI'			=> $this->post('ALMTBELI'),
					'NEGBELI'			=> $this->post('NEGBELI'),
					'IDPPJK'			=> $this->post('IDPPJK'),
					'NPWPPPJK'			=> $this->post('NPWPPPJK'),
					'NamaPpjk'			=> $this->post('NamaPpjk'),
					'AlmtPpjk'			=> $this->post('AlmtPpjk'),
					'NoPpjk'			=> $this->post('NoPpjk'),
					'TgPpjk'			=> $this->post('TgPpjk'),
					'MODA'				=> $this->post('MODA'),
					'TGEKS'				=> $this->post('TGEKS'),
					'CARRIER'			=> $this->post('CARRIER'),
					'VOY'				=> $this->post('VOY'),
					'NOSHIPORD'			=> $this->post('NOSHIPORD'),
					'TGSHIPORD'			=> $this->post('TGSHIPORD'),
					'PELMUAT'			=> $this->post('PELMUAT'),
					'PELBONGKAR'		=> $this->post('PELBONGKAR'),
					'PELTRANSIT'		=> $this->post('PELTRANSIT'),
					'NOINV'				=> $this->post('NOINV'),
					'TGINV'				=> $this->post('TGINV'),
					'NOLPSE'			=> $this->post('NOLPSE'),
					'TGLPSE'			=> $this->post('TGLPSE'),
					'PROPBRG'			=> $this->post('PROPBRG'),
					'NEGTUJU'			=> $this->post('NEGTUJU'),
					'FLSIE'				=> $this->post('FLSIE'),
					'FLKARANT'			=> $this->post('FLKARANT'),
					'FLSM'				=> $this->post('FLSM'),
					'FLIZLAIN'			=> $this->post('FLIZLAIN'),
					'DELIVERY'			=> $this->post('DELIVERY'),
					'KDVAL'				=> $this->post('KDVAL'),
					'KdHrg'				=> $this->post('KdHrg'),
					'NilInv'			=> $this->post('NilInv'),
					'FREIGHT'			=> $this->post('FREIGHT'),
					'ASURANSI'			=> $this->post('ASURANSI'),
					'KdAss'				=> $this->post('KdAss'),
					'FOB'				=> $this->post('FOB'),
					'MERK'				=> $this->post('MERK'),
					'JMCONT'			=> $this->post('JMCONT'),
					'BRUTO'				=> $this->post('BRUTO'),
					'NETTO'				=> $this->post('NETTO'),
					'JMBRG'				=> $this->post('JMBRG'),
					'JMBRGCTH'			=> $this->post('JMBRGCTH'),
					'JMBRGGAB'			=> $this->post('JMBRGGAB'),
					'JMBRGPJT'			=> $this->post('JMBRGPJT'),
					'NODAFT'			=> $this->post('NODAFT'),
					'TGDAFT'			=> $this->post('TGDAFT'),
					'KDKTR'				=> $this->post('KDKTR'),
					'KTRGATE'			=> $this->post('KTRGATE'),
					'NILPE'				=> $this->post('NILPE'),
					'KDBANK'			=> $this->post('KDBANK'),
					'LOKBANK'			=> $this->post('LOKBANK'),
					'NOSSP'				=> $this->post('NOSSP'),
					'TGSSP'				=> $this->post('TGSSP'),
					'JNTPB'				=> $this->post('JNTPB'),
					'LOKTPB'			=> $this->post('LOKTPB'),
					'KDLOKBRG'			=> $this->post('KDLOKBRG'),
					'KDKTRMUAT'			=> $this->post('KDKTRMUAT'),
					'KDKTRPRIKS'		=> $this->post('KDKTRPRIKS'),
					'TGSIAP'			=> $this->post('TGSIAP'),
					'WKSIAP'			=> $this->post('WKSIAP'),
					'ASALDATA'			=> $this->post('ASALDATA'),
					'TPNAME'			=> $this->post('TPNAME'),
					'PEBOK'				=> $this->post('PEBOK'),
					'LENGKAP'			=> $this->post('LENGKAP'),
					'JNPARTOF'			=> $this->post('JNPARTOF'),
					'BENDERA'			=> $this->post('BENDERA'),
					'TTDPEB'			=> $this->post('TTDPEB'),
					'STATUS'			=> $this->post('STATUS'),
					'SNRF'				=> $this->post('SNRF'),
					'NOBCF'				=> $this->post('NOBCF'),
					'TGBCF'				=> $this->post('TGBCF'),
					'SERIBCF'			=> $this->post('SERIBCF'),
					'NOMOREDI'			=> $this->post('NOMOREDI'),
					'KMDT'				=> $this->post('KMDT'),
					'VOLUME'			=> $this->post('VOLUME'),
					'KDHANGGAR'			=> $this->post('KDHANGGAR'),
					'KONS'				=> $this->post('KONS'),
					'JMLKMSPEB'			=> $this->post('JMLKMSPEB'),
					'PELMUATEKS'		=> $this->post('PELMUATEKS'),
					'NILKURS'			=> $this->post('NILKURS'),
					'PNBP'				=> $this->post('PNBP'),
					'NOBC11'			=> $this->post('NOBC11'),
					'TGBC11'			=> $this->post('TGBC11'),
					'POSBC11'			=> $this->post('POSBC11'),
					'SUBPOSBC11'		=> $this->post('SUBPOSBC11'),
					'TGL_BERLAKU_TOD'	=> $this->post('TGL_BERLAKU_TOD'),
					'KDKTREKS'			=> $this->post('KDKTREKS'),
					'PELTUJUAN'			=> $this->post('PELTUJUAN'),
					'NAMABELI2'			=> $this->post('NAMABELI2'),
					'ALMTBELI2'			=> $this->post('ALMTBELI2'),
					'NEGBELI2'			=> $this->post('NEGBELI2'),
					'VERSIMODUL'		=> $this->post('VERSIMODUL'),
					'NILMAKLON'			=> $this->post('NILMAKLON'),
					'NILPAJAKLAIN'		=> $this->post('NILPAJAKLAIN'),
					'URCARABAYAR'		=> $this->post('URCARABAYAR'),
					'GUDANGPLB'			=> $this->post('GUDANGPLB'),
					'PERNYATAAN'		=> $this->post('PERNYATAAN'),
					'flKdVAL'			=> $this->post('flKdVAL'),
					'flFOB'				=> $this->post('flFOB'),
					'flNilMaklon'		=> $this->post('flNilMaklon')
					);
					
		 $insert = $this->db->insert('temp_pebhdr', $data);
        if ($insert) {
            $this->response($data, 200);
        } else {
            $this->response(array('status' => 'fail', 502));
        }
	}
}